### ISSUE TITLE
ID Display doesn't ID Name

### ISSUE THREAD

**Issue by Chemscribbler** [AlexRodwell/netrunner-stream-overlay#7]
I was assuming ID display would display some shortname for the Identity, rather than the faction - but probably just renaming the button faction for now is good enough :D 

I think ID (like 419: Amoral Scammer or 419) is probably more relevant in case of fancy alt arts

**Comment by AlexRodwell** [comment]
I did previously have it so that it striped anything after the first colon so that it would simply be '419` and disregard the flavour text, relatively easy to add back, could also make it a toggle state too.

**Comment by AlexRodwell** [comment]
Fixed in the referenced commit (hopefully), it now looks like this:
![image](https://github.com/AlexRodwell/netrunner-stream-overlay/assets/9072533/58236e3f-9752-46df-ace7-930a3c065ac1)

It simply checks if the ID has a colon in it, if true, remove that and everything after, to return just the name: `{data.id.includes(":") ? data.id.replace(/:.*/, "") : data.id}`
